name = "stochastic_damped_harmonic_oscillator"
version = "0.1.0"
license = "license"
author = "Julian Iacoponi"
maintainer = "julian.iacoponi@gmail.com"
copyright = "Copyright 2023, Julian Iacoponi"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
stdlib.git = "https://github.com/fortran-lang/stdlib"
stdlib.branch = "stdlib-fpm"
